on: [push]
jobs:
  display_files:
    name: run a sample command
    runs-on: windows-latest
    steps:        
      - name: display output
        run: |
          echo "Hello World"
        shell: bash
